# coding: utf-8

"""
    Studio Notification

    For creating and managing Aladdin Studio notifications.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class V1StudioRecipientType(str, Enum):
    """
    - STUDIO_RECIPIENT_TYPE_UNSPECIFIED: Unspecified  - STUDIO_RECIPIENT_TYPE_USER: User  - STUDIO_RECIPIENT_TYPE_EMAIL: Email  - STUDIO_RECIPIENT_TYPE_PROJECT: Project  - STUDIO_RECIPIENT_TYPE_SPACE: Space  - STUDIO_RECIPIENT_TYPE_PERM: PERMS
    """

    """
    allowed enum values
    """
    STUDIO_RECIPIENT_TYPE_UNSPECIFIED = 'STUDIO_RECIPIENT_TYPE_UNSPECIFIED'
    STUDIO_RECIPIENT_TYPE_USER = 'STUDIO_RECIPIENT_TYPE_USER'
    STUDIO_RECIPIENT_TYPE_EMAIL = 'STUDIO_RECIPIENT_TYPE_EMAIL'
    STUDIO_RECIPIENT_TYPE_PROJECT = 'STUDIO_RECIPIENT_TYPE_PROJECT'
    STUDIO_RECIPIENT_TYPE_SPACE = 'STUDIO_RECIPIENT_TYPE_SPACE'
    STUDIO_RECIPIENT_TYPE_PERM = 'STUDIO_RECIPIENT_TYPE_PERM'

    @classmethod
    def from_json(cls, json_str: str) -> V1StudioRecipientType:
        """Create an instance of V1StudioRecipientType from a JSON string"""
        return V1StudioRecipientType(json.loads(json_str))


