# coding: utf-8

"""
    Engagement

    Create, modify, delete, retrieve, search and historical engagement search.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr
from aladdinsdk.api.codegen.investment_research.content.engagement.v1.engagement.models.v1_expiring_permission_time_unit import V1ExpiringPermissionTimeUnit

class V1ExpiringPermissionGroup(BaseModel):
    """
    V1ExpiringPermissionGroup
    """
    permission_group: Optional[StrictStr] = Field(None, alias="permissionGroup")
    time_unit: Optional[V1ExpiringPermissionTimeUnit] = Field(None, alias="timeUnit")
    time_span: Optional[StrictInt] = Field(None, alias="timeSpan")
    __properties = ["permissionGroup", "timeUnit", "timeSpan"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> V1ExpiringPermissionGroup:
        """Create an instance of V1ExpiringPermissionGroup from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> V1ExpiringPermissionGroup:
        """Create an instance of V1ExpiringPermissionGroup from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return V1ExpiringPermissionGroup.parse_obj(obj)

        _obj = V1ExpiringPermissionGroup.parse_obj({
            "permission_group": obj.get("permissionGroup"),
            "time_unit": obj.get("timeUnit"),
            "time_span": obj.get("timeSpan")
        })
        return _obj

