# coding: utf-8

"""
    Cash Ladder

    Cash Ladder provides a settlement date based ladder of cash balances for all the exposure currencies for a given portfolio group and cash date.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class EnumsopenDate(str, Enum):
    """
    This field represents the future date up to which order activity is to be retrieved.   - OPEN_DATE_UNSPECIFIED: Default setting. Get cash impact of orders having open date today (T)  - OPEN_DATE_T: Get cash impact of orders having open date today (T)  - OPEN_DATE_UP_TO_T1: Get cash impact of orders having open date up to tomorrow (T+1)  - OPEN_DATE_UP_TO_T2: Get cash impact of orders having open date up to 2 days from today (T+2)  - OPEN_DATE_UP_TO_T3: Get cash impact of orders having open date up to 3 days from today (T+3)  - OPEN_DATE_ALL: Get cash impact of all orders having open date greater than or equal to today (T)
    """

    """
    allowed enum values
    """
    OPEN_DATE_UNSPECIFIED = 'OPEN_DATE_UNSPECIFIED'
    OPEN_DATE_T = 'OPEN_DATE_T'
    OPEN_DATE_UP_TO_T1 = 'OPEN_DATE_UP_TO_T1'
    OPEN_DATE_UP_TO_T2 = 'OPEN_DATE_UP_TO_T2'
    OPEN_DATE_UP_TO_T3 = 'OPEN_DATE_UP_TO_T3'
    OPEN_DATE_ALL = 'OPEN_DATE_ALL'

    @classmethod
    def from_json(cls, json_str: str) -> EnumsopenDate:
        """Create an instance of EnumsopenDate from a JSON string"""
        return EnumsopenDate(json.loads(json_str))


