# coding: utf-8

"""
    Research Note

    Create, modify, delete and retrieve research notes.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class V1InvestmentStewardshipScore(str, Enum):
    """
    - INVESTMENT_STEWARDSHIP_SCORE_UNSPECIFIED: N/A  - INVESTMENT_STEWARDSHIP_SCORE_POSITIVE: positive  - INVESTMENT_STEWARDSHIP_SCORE_NEUTRAL: neutral  - INVESTMENT_STEWARDSHIP_SCORE_NEGATIVE: negative
    """

    """
    allowed enum values
    """
    INVESTMENT_STEWARDSHIP_SCORE_UNSPECIFIED = 'INVESTMENT_STEWARDSHIP_SCORE_UNSPECIFIED'
    INVESTMENT_STEWARDSHIP_SCORE_POSITIVE = 'INVESTMENT_STEWARDSHIP_SCORE_POSITIVE'
    INVESTMENT_STEWARDSHIP_SCORE_NEUTRAL = 'INVESTMENT_STEWARDSHIP_SCORE_NEUTRAL'
    INVESTMENT_STEWARDSHIP_SCORE_NEGATIVE = 'INVESTMENT_STEWARDSHIP_SCORE_NEGATIVE'

    @classmethod
    def from_json(cls, json_str: str) -> V1InvestmentStewardshipScore:
        """Create an instance of V1InvestmentStewardshipScore from a JSON string"""
        return V1InvestmentStewardshipScore(json.loads(json_str))


