# coding: utf-8

"""
    Research Note

    Create, modify, delete and retrieve research notes.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class V1InvestmentStewardshipFormat(str, Enum):
    """
    - INVESTMENT_STEWARDSHIP_FORMAT_UNSPECIFIED: Unspecified  - INVESTMENT_STEWARDSHIP_FORMAT_IN_PERSON: In person  - INVESTMENT_STEWARDSHIP_FORMAT_CONF_CALL: Conference Call  - INVESTMENT_STEWARDSHIP_FORMAT_EMAIL: Email  - INVESTMENT_STEWARDSHIP_FORMAT_INTERNAL_TRACKING: Internal tracking
    """

    """
    allowed enum values
    """
    INVESTMENT_STEWARDSHIP_FORMAT_UNSPECIFIED = 'INVESTMENT_STEWARDSHIP_FORMAT_UNSPECIFIED'
    INVESTMENT_STEWARDSHIP_FORMAT_IN_PERSON = 'INVESTMENT_STEWARDSHIP_FORMAT_IN_PERSON'
    INVESTMENT_STEWARDSHIP_FORMAT_CONF_CALL = 'INVESTMENT_STEWARDSHIP_FORMAT_CONF_CALL'
    INVESTMENT_STEWARDSHIP_FORMAT_EMAIL = 'INVESTMENT_STEWARDSHIP_FORMAT_EMAIL'
    INVESTMENT_STEWARDSHIP_FORMAT_INTERNAL_TRACKING = 'INVESTMENT_STEWARDSHIP_FORMAT_INTERNAL_TRACKING'

    @classmethod
    def from_json(cls, json_str: str) -> V1InvestmentStewardshipFormat:
        """Create an instance of V1InvestmentStewardshipFormat from a JSON string"""
        return V1InvestmentStewardshipFormat(json.loads(json_str))


