# coding: utf-8

"""
    Aladdin Corporate Action

    A corporate action is an event triggered by a public company that changes an equity or fixed income security issued by the company. There are two main categories - Mandatory and Voluntary.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class V1TaxCode(str, Enum):
    """
    Enumeration of tax codes.   - TAX_CODE_UNSPECIFIED: Reserved value. Default value if not specified.  - TAX_CODE_TAXABLE: TAXABLE.  - TAX_CODE_S302: Section 302.  - TAX_CODE_NOT_TAXABLE: NON_TAXABLE.
    """

    """
    allowed enum values
    """
    TAX_CODE_UNSPECIFIED = 'TAX_CODE_UNSPECIFIED'
    TAX_CODE_TAXABLE = 'TAX_CODE_TAXABLE'
    TAX_CODE_S302 = 'TAX_CODE_S302'
    TAX_CODE_NOT_TAXABLE = 'TAX_CODE_NOT_TAXABLE'

    @classmethod
    def from_json(cls, json_str: str) -> V1TaxCode:
        """Create an instance of V1TaxCode from a JSON string"""
        return V1TaxCode(json.loads(json_str))


