# coding: utf-8

"""
    Research Note

    Create, modify, delete and retrieve research notes.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class V2TemplateState(str, Enum):
    """
    - TEMPLATE_STATE_UNSPECIFIED: Unspecified  - TEMPLATE_STATE_DRAFT: Draft  - TEMPLATE_STATE_ACTIVE: Active  - TEMPLATE_STATE_INACTIVE: Inactive
    """

    """
    allowed enum values
    """
    TEMPLATE_STATE_UNSPECIFIED = 'TEMPLATE_STATE_UNSPECIFIED'
    TEMPLATE_STATE_DRAFT = 'TEMPLATE_STATE_DRAFT'
    TEMPLATE_STATE_ACTIVE = 'TEMPLATE_STATE_ACTIVE'
    TEMPLATE_STATE_INACTIVE = 'TEMPLATE_STATE_INACTIVE'

    @classmethod
    def from_json(cls, json_str: str) -> V2TemplateState:
        """Create an instance of V2TemplateState from a JSON string"""
        return V2TemplateState(json.loads(json_str))


