# coding: utf-8

# flake8: noqa

"""
    Aladdin User Group Permission

    API contains operations on Aladdin User Group Permission resource. Note: This is not intended to be used for Authorization.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


__version__ = "1.0.0"

# import apis into sdk package
from aladdinsdk.api.codegen.platform.access.permission.v1.user_group_permission.api.default_user_group_permission_api import DefaultUserGroupPermissionAPI

# import ApiClient
from aladdinsdk.api.codegen.platform.access.permission.v1.user_group_permission.api_response import ApiResponse
from aladdinsdk.api.codegen.platform.access.permission.v1.user_group_permission.api_client import ApiClient
from aladdinsdk.api.codegen.platform.access.permission.v1.user_group_permission.configuration import Configuration
from aladdinsdk.api.codegen.platform.access.permission.v1.user_group_permission.exceptions import OpenApiException
from aladdinsdk.api.codegen.platform.access.permission.v1.user_group_permission.exceptions import ApiTypeError
from aladdinsdk.api.codegen.platform.access.permission.v1.user_group_permission.exceptions import ApiValueError
from aladdinsdk.api.codegen.platform.access.permission.v1.user_group_permission.exceptions import ApiKeyError
from aladdinsdk.api.codegen.platform.access.permission.v1.user_group_permission.exceptions import ApiAttributeError
from aladdinsdk.api.codegen.platform.access.permission.v1.user_group_permission.exceptions import ApiException

# import models into sdk package
from aladdinsdk.api.codegen.platform.access.permission.v1.user_group_permission.models.any import Any
from aladdinsdk.api.codegen.platform.access.permission.v1.user_group_permission.models.rpc_status import RpcStatus
from aladdinsdk.api.codegen.platform.access.permission.v1.user_group_permission.models.user_group_permission_api_batch_create_user_group_permissions_request import UserGroupPermissionAPIBatchCreateUserGroupPermissionsRequest
from aladdinsdk.api.codegen.platform.access.permission.v1.user_group_permission.models.user_group_permission_api_batch_delete_user_group_permission_request import UserGroupPermissionAPIBatchDeleteUserGroupPermissionRequest
from aladdinsdk.api.codegen.platform.access.permission.v1.user_group_permission.models.user_group_permission_api_list_user_group_permissions400_response import UserGroupPermissionAPIListUserGroupPermissions400Response
from aladdinsdk.api.codegen.platform.access.permission.v1.user_group_permission.models.v1_batch_create_user_group_permissions_response import V1BatchCreateUserGroupPermissionsResponse
from aladdinsdk.api.codegen.platform.access.permission.v1.user_group_permission.models.v1_create_user_group_permission_request import V1CreateUserGroupPermissionRequest
from aladdinsdk.api.codegen.platform.access.permission.v1.user_group_permission.models.v1_delete_user_group_permission_request import V1DeleteUserGroupPermissionRequest
from aladdinsdk.api.codegen.platform.access.permission.v1.user_group_permission.models.v1_list_user_group_permissions_response import V1ListUserGroupPermissionsResponse
from aladdinsdk.api.codegen.platform.access.permission.v1.user_group_permission.models.v1_user_group_permission import V1UserGroupPermission
