# flake8: noqa

# import apis into api package
from aladdinsdk.api.codegen.investment_operations.reference_data.broker.v1.counterparty_settlement_instruction_template.api.default_counter_party_settlement_instruction_template_api import DefaultCounterPartySettlementInstructionTemplateAPI

