# coding: utf-8

# flake8: noqa

"""
    Custom Investment Dataset Reader

    API for reading Dataset Definitions and Entities.  _CIDS does not transform the input data in any kind. The writer of the data owns it and is responsible for this data. CIDS provides a way to ingest the custom investment data into Aladdin for usage across Portfolio Management tools._  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


__version__ = "1.0.0"

# import apis into sdk package
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.api.default_cid_reader_api import DefaultCIDReaderAPI

# import ApiClient
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.api_response import ApiResponse
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.api_client import ApiClient
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.configuration import Configuration
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.exceptions import OpenApiException
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.exceptions import ApiTypeError
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.exceptions import ApiValueError
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.exceptions import ApiKeyError
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.exceptions import ApiAttributeError
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.exceptions import ApiException

# import models into sdk package
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.models.any import Any
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.models.cid_reader_api_remove_datasets400_response import CIDReaderAPIRemoveDatasets400Response
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.models.rpc_status import RpcStatus
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.models.v1_attribute_agg import V1AttributeAgg
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.models.v1_attribute_type import V1AttributeType
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.models.v1_cid_dataset_definition import V1CIDDatasetDefinition
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.models.v1_cid_dataset_hierarchy import V1CIDDatasetHierarchy
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.models.v1_cid_dataset_schema import V1CIDDatasetSchema
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.models.v1_cid_dataset_schema_attribute import V1CIDDatasetSchemaAttribute
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.models.v1_cid_dataset_schema_entity import V1CIDDatasetSchemaEntity
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.models.v1_cid_entity import V1CIDEntity
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.models.v1_dataset_type import V1DatasetType
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.models.v1_date_time_range import V1DateTimeRange
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.models.v1_entity_name_list import V1EntityNameList
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.models.v1_filter_cid_entities_request import V1FilterCIDEntitiesRequest
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.models.v1_filter_cid_entities_response import V1FilterCIDEntitiesResponse
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.models.v1_list_cid_dataset_definitions_response import V1ListCIDDatasetDefinitionsResponse
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.models.v1_list_cid_entity_response import V1ListCIDEntityResponse
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.models.v1_perm_group import V1PermGroup
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.models.v1_portfolio_name_list import V1PortfolioNameList
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.models.v1_purpose import V1Purpose
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.models.v1_remove_datasets_request import V1RemoveDatasetsRequest
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.models.v1_remove_datasets_response import V1RemoveDatasetsResponse
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.models.v1_schema_attribute_criteria import V1SchemaAttributeCriteria
from aladdinsdk.api.codegen.portfolio_management.setup.cids.v1.cids_reader.models.v1_state import V1State
