# coding: utf-8

"""
    Cash Ladder

    Cash Ladder provides a settlement date based ladder of cash balances for all the exposure currencies for a given portfolio group and cash date.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class EnumstradeDate(str, Enum):
    """
    This field represents the future trade date up to which trade activity is to be retrieved.   - TRADE_DATE_UNSPECIFIED: Get cash impact of trades having trade date today (T)  - TRADE_DATE_T: Get cash impact of trades having trade date today (T)  - TRADE_DATE_UP_TO_T1: Get cash impact of trades having trade date up to tomorrow (T+1)  - TRADE_DATE_UP_TO_T2: Get cash impact of trades having trade date up to 2 days from today (T+2)  - TRADE_DATE_UP_TO_T3: Get cash impact of trades having trade date up to 3 days from today (T+3)  - TRADE_DATE_ALL: Get cash impact of all trades having trade date greater than or equal to today (T)
    """

    """
    allowed enum values
    """
    TRADE_DATE_UNSPECIFIED = 'TRADE_DATE_UNSPECIFIED'
    TRADE_DATE_T = 'TRADE_DATE_T'
    TRADE_DATE_UP_TO_T1 = 'TRADE_DATE_UP_TO_T1'
    TRADE_DATE_UP_TO_T2 = 'TRADE_DATE_UP_TO_T2'
    TRADE_DATE_UP_TO_T3 = 'TRADE_DATE_UP_TO_T3'
    TRADE_DATE_ALL = 'TRADE_DATE_ALL'

    @classmethod
    def from_json(cls, json_str: str) -> EnumstradeDate:
        """Create an instance of EnumstradeDate from a JSON string"""
        return EnumstradeDate(json.loads(json_str))


