# coding: utf-8

"""
    Broker Desk

    API contains operations on Broker Desk resource.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field
from aladdinsdk.api.codegen.investment_operations.reference_data.broker.v1.broker_desk.models.v1_broker_desk import V1BrokerDesk

class V1UpdateBrokerDeskRequest(BaseModel):
    """
    V1UpdateBrokerDeskRequest
    """
    broker_desk: Optional[V1BrokerDesk] = Field(None, alias="brokerDesk")
    __properties = ["brokerDesk"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> V1UpdateBrokerDeskRequest:
        """Create an instance of V1UpdateBrokerDeskRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of broker_desk
        if self.broker_desk:
            _dict['brokerDesk'] = self.broker_desk.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> V1UpdateBrokerDeskRequest:
        """Create an instance of V1UpdateBrokerDeskRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return V1UpdateBrokerDeskRequest.parse_obj(obj)

        _obj = V1UpdateBrokerDeskRequest.parse_obj({
            "broker_desk": V1BrokerDesk.from_dict(obj.get("brokerDesk")) if obj.get("brokerDesk") is not None else None
        })
        return _obj

