# coding: utf-8

# flake8: noqa
"""
    Climate

    The Aladdin Climate Data API exposes physical, transition, and temperature alignment analytics as of a given date. Users can retrieve data for selected entity types by specifying the desired datapoints for each climate risk type and scenario. The Aladdin Climate Meta Data API outlines the datapoints available across physical, transition, and temperature alignment analytics.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


# import models into model package
from aladdinsdk.api.codegen.analytics.data.climate.v1.ClimateAPI.models.any import Any
from aladdinsdk.api.codegen.analytics.data.climate.v1.ClimateAPI.models.climate_api_retrieve_climate_data_as_of_date400_response import ClimateAPIRetrieveClimateDataAsOfDate400Response
from aladdinsdk.api.codegen.analytics.data.climate.v1.ClimateAPI.models.climatev1_segment import Climatev1Segment
from aladdinsdk.api.codegen.analytics.data.climate.v1.ClimateAPI.models.rpc_status import RpcStatus
from aladdinsdk.api.codegen.analytics.data.climate.v1.ClimateAPI.models.types_analytic_data_value import TypesAnalyticDataValue
from aladdinsdk.api.codegen.analytics.data.climate.v1.ClimateAPI.models.v1_climate_common_data_set import V1ClimateCommonDataSet
from aladdinsdk.api.codegen.analytics.data.climate.v1.ClimateAPI.models.v1_climate_common_metrics import V1ClimateCommonMetrics
from aladdinsdk.api.codegen.analytics.data.climate.v1.ClimateAPI.models.v1_climate_data_set import V1ClimateDataSet
from aladdinsdk.api.codegen.analytics.data.climate.v1.ClimateAPI.models.v1_climate_data_set_response import V1ClimateDataSetResponse
from aladdinsdk.api.codegen.analytics.data.climate.v1.ClimateAPI.models.v1_climate_metadata import V1ClimateMetadata
from aladdinsdk.api.codegen.analytics.data.climate.v1.ClimateAPI.models.v1_climate_risk_request import V1ClimateRiskRequest
from aladdinsdk.api.codegen.analytics.data.climate.v1.ClimateAPI.models.v1_climate_scenario import V1ClimateScenario
from aladdinsdk.api.codegen.analytics.data.climate.v1.ClimateAPI.models.v1_climate_scenario_data_set import V1ClimateScenarioDataSet
from aladdinsdk.api.codegen.analytics.data.climate.v1.ClimateAPI.models.v1_common_metric_value import V1CommonMetricValue
from aladdinsdk.api.codegen.analytics.data.climate.v1.ClimateAPI.models.v1_data_type import V1DataType
from aladdinsdk.api.codegen.analytics.data.climate.v1.ClimateAPI.models.v1_field_mapping import V1FieldMapping
from aladdinsdk.api.codegen.analytics.data.climate.v1.ClimateAPI.models.v1_id_attributes import V1IdAttributes
from aladdinsdk.api.codegen.analytics.data.climate.v1.ClimateAPI.models.v1_id_type import V1IdType
from aladdinsdk.api.codegen.analytics.data.climate.v1.ClimateAPI.models.v1_metric import V1Metric
from aladdinsdk.api.codegen.analytics.data.climate.v1.ClimateAPI.models.v1_metric_type import V1MetricType
from aladdinsdk.api.codegen.analytics.data.climate.v1.ClimateAPI.models.v1_metric_value import V1MetricValue
from aladdinsdk.api.codegen.analytics.data.climate.v1.ClimateAPI.models.v1_model_parameter import V1ModelParameter
from aladdinsdk.api.codegen.analytics.data.climate.v1.ClimateAPI.models.v1_output_value import V1OutputValue
from aladdinsdk.api.codegen.analytics.data.climate.v1.ClimateAPI.models.v1_regional_segment import V1RegionalSegment
from aladdinsdk.api.codegen.analytics.data.climate.v1.ClimateAPI.models.v1_retrieve_climate_data_as_of_date_request import V1RetrieveClimateDataAsOfDateRequest
from aladdinsdk.api.codegen.analytics.data.climate.v1.ClimateAPI.models.v1_retrieve_climate_metadata_response import V1RetrieveClimateMetadataResponse
from aladdinsdk.api.codegen.analytics.data.climate.v1.ClimateAPI.models.v1_scenario_option import V1ScenarioOption
