# coding: utf-8

"""
    Security Creation

    This service is used to create CDS, CDX, Equity Equity, Equity Option, Futures, FX NDF, FX SPOT, FX FWRD, FX CSWAP, FX Option, Swap, Swaption, CASH/TD, CASH/REPO, ARM/TBA and MBS/TBA securities.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class EnumsFXType(str, Enum):
    """
    - FX_TYPE_UNSPECIFIED: UNSPECIFIED  - FX_TYPE_SPOT: SPOT  - FX_TYPE_FORWARD: FORWARD  - FX_TYPE_CSWAP: CSWAP
    """

    """
    allowed enum values
    """
    FX_TYPE_UNSPECIFIED = 'FX_TYPE_UNSPECIFIED'
    FX_TYPE_SPOT = 'FX_TYPE_SPOT'
    FX_TYPE_FORWARD = 'FX_TYPE_FORWARD'
    FX_TYPE_CSWAP = 'FX_TYPE_CSWAP'

    @classmethod
    def from_json(cls, json_str: str) -> EnumsFXType:
        """Create an instance of EnumsFXType from a JSON string"""
        return EnumsFXType(json.loads(json_str))


