# coding: utf-8

"""
    Security Analytics Compute

    Compute security level analytics, cash flows and scenario analytics with custom valuation settings.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class InflationConfigInflationProjectionType(str, Enum):
    """
    - INFLATION_PROJECTION_TYPE_UNSPECIFIED: Default value  - INFLATION_PROJECTION_TYPE_GOVERNMENT_TERM_STRUCTURE: Represents an input to use Government Term Structure  - INFLATION_PROJECTION_TYPE_SWAP_TERM_STRUCTURE: Represents an input to use Swap Term Structure  - INFLATION_PROJECTION_TYPE_CONSTANT: Represents a constant inflation rate
    """

    """
    allowed enum values
    """
    INFLATION_PROJECTION_TYPE_UNSPECIFIED = 'INFLATION_PROJECTION_TYPE_UNSPECIFIED'
    INFLATION_PROJECTION_TYPE_GOVERNMENT_TERM_STRUCTURE = 'INFLATION_PROJECTION_TYPE_GOVERNMENT_TERM_STRUCTURE'
    INFLATION_PROJECTION_TYPE_SWAP_TERM_STRUCTURE = 'INFLATION_PROJECTION_TYPE_SWAP_TERM_STRUCTURE'
    INFLATION_PROJECTION_TYPE_CONSTANT = 'INFLATION_PROJECTION_TYPE_CONSTANT'

    @classmethod
    def from_json(cls, json_str: str) -> InflationConfigInflationProjectionType:
        """Create an instance of InflationConfigInflationProjectionType from a JSON string"""
        return InflationConfigInflationProjectionType(json.loads(json_str))


