# coding: utf-8

"""
    Security Analytics Compute

    Compute security level analytics, cash flows and scenario analytics with custom valuation settings.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class PricingConfigPricingInputType(str, Enum):
    """
    - PRICING_INPUT_TYPE_UNSPECIFIED: Default value  - PRICING_INPUT_TYPE_PRICE: Represent an input which is a direct price  - PRICING_INPUT_TYPE_SHORTCUT: Represents an input specified in shortcut form
    """

    """
    allowed enum values
    """
    PRICING_INPUT_TYPE_UNSPECIFIED = 'PRICING_INPUT_TYPE_UNSPECIFIED'
    PRICING_INPUT_TYPE_PRICE = 'PRICING_INPUT_TYPE_PRICE'
    PRICING_INPUT_TYPE_SHORTCUT = 'PRICING_INPUT_TYPE_SHORTCUT'

    @classmethod
    def from_json(cls, json_str: str) -> PricingConfigPricingInputType:
        """Create an instance of PricingConfigPricingInputType from a JSON string"""
        return PricingConfigPricingInputType(json.loads(json_str))


