# coding: utf-8

# flake8: noqa
"""
    Timeseries

    Timeseries offers a unified interface for researchers to retrieve, update and delete timeseries data that are stored in Snowflake.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


# import models into model package
from aladdinsdk.api.codegen.investment_research.data_services.timeseries.v1.TimeseriesAPI.models.any import Any
from aladdinsdk.api.codegen.investment_research.data_services.timeseries.v1.TimeseriesAPI.models.rpc_status import RpcStatus
from aladdinsdk.api.codegen.investment_research.data_services.timeseries.v1.TimeseriesAPI.models.timeseries_api_delete_timeseries400_response import TimeseriesAPIDeleteTimeseries400Response
from aladdinsdk.api.codegen.investment_research.data_services.timeseries.v1.TimeseriesAPI.models.v1_retrieve_timeseries_request import V1RetrieveTimeseriesRequest
from aladdinsdk.api.codegen.investment_research.data_services.timeseries.v1.TimeseriesAPI.models.v1_timeseries import V1Timeseries
from aladdinsdk.api.codegen.investment_research.data_services.timeseries.v1.TimeseriesAPI.models.v1_timeseries_query import V1TimeseriesQuery
from aladdinsdk.api.codegen.investment_research.data_services.timeseries.v1.TimeseriesAPI.models.v1_timeseries_row import V1TimeseriesRow
from aladdinsdk.api.codegen.investment_research.data_services.timeseries.v1.TimeseriesAPI.models.v1_upload_mode import V1UploadMode
